on:
  push:
    branches:
      - main
    paths-ignore:
    - 'actions/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Action Server image and upgrade Rasa X deployment
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - id: action_server
      name: Build an action server with a custom actions
      uses: RasaHQ/action-server-gha@main
      # Full list of parameters: https://github.com/RasaHQ/action-server-gha/tree/master#input-arguments
      with:
        docker_image_name: 'andreasmartinfhnw/ayo-action'
        docker_registry: 'https://ghcr.io'
        docker_registry_login: ${{ github.actor }} #${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.GITHUB_TOKEN }} #${{ secrets.DOCKER_HUB_PASSWORD }}
        # More details about github context:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        #
        # github.sha - The commit SHA that triggered the workflow run
        docker_image_tag: latest,${{ github.sha }}
