on:
  push:
    branches:
      - main
    paths:
    - 'actions/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Action Server image and upgrade Rasa X deployment
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - id: action_server
      name: Build an action server with a custom actions
      uses: RasaHQ/action-server-gha@main
      with:
        docker_image_name: 'hivbot/ayo-rasa' #'andreasmartinfhnw/ayo-action'
        docker_registry: 'ghcr.io'
        docker_registry_login: ${{ github.actor }} #${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.GITHUB_TOKEN }} #${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_image_tag: latest #${{ github.sha }}
