name: Deploy Model

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Model
      uses: fjogeleit/http-request-action@v1
      with:
        url: '${{ secrets.RASA_HTTP_API }}/model?token=${{ secrets.RASA_TOKEN }}'
        method: 'PUT'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"model_server":{"url":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/latest/model.tar.gz","wait_time_between_pulls":null}}'
        preventFailureOnNoResponse: 'true'
