'on':
  push:
    branches:
      - main
    paths-ignore:
      - data/**
jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: latest-full
          #requirements_file: requirements.txt
          #data_validate: true
          rasa_train: true
          #cross_validation: true
          #rasa_test: true
          #test_type: all
          #publish_summary: true
          github_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Upload model
        uses: actions/upload-artifact@main
        with:
          name: model
          path: models
