name: Model Train

'on':
  push:
    branches:
      - main
    paths:
      - data/**

jobs:
  training-testing-upload-pull:
    name: Training, Testing, Upload and Pull
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: latest-full
          #requirements_file: requirements.txt
          #data_validate: true
          rasa_train: true
          train_type: nlu
          train_args: --fixed-model-name model
          #cross_validation: true
          rasa_test: true
          test_type: nlu
          #publish_summary: true
          github_token: '${{ secrets.GITHUB_TOKEN }}'
      - id: upload-model
        name: Upload model
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Development Build"
          files: |
            models/model.tar.gz
      - name: Pull Model
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.RASA_HTTP_API }}/model?token=${{ secrets.RASA_TOKEN }}'
          method: 'PUT'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"model_server":{"url":"${{github.server_url}}/${{github.repository}}/releases/download/${{ steps.upload-model.outputs.automatic_releases_tag }}/model.tar.gz","wait_time_between_pulls":null}}'
          preventFailureOnNoResponse: 'true'
