'on':
  push:
    branches:
      - main
    paths-ignore:
      - data/**
jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: latest-full
          #requirements_file: requirements.txt
          #data_validate: true
          rasa_train: true
          train_args: --fixed-model-name model
          #cross_validation: true
          #rasa_test: true
          #test_type: all
          #publish_summary: true
          github_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Upload model
        #uses: actions/upload-artifact@main
        #with:
          #name: model
          #path: models
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add models/
          git commit -am "Upload model" \
          && git push origin HEAD:main \
          || true
